server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 1
      logic-delete-value: 0